import type { Metadata } from "next";
import "./globals.css";
import MyCustomFont from "../../public/assets/fonts/fonts";
import NavbarComponent from "@/app/components/Navbar/Navbar";
import FooterComponent from "@/app/components/Footer/Footer";
import Canonical from "./components/Canonical-Component/Canonical";

export const metadata: Metadata = {
  title: "Techtimize",
  description: "Generated by create next app",
   icons: {
        icon: '/favicon.ico'
    },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Canonical /> 
      <body className={`${MyCustomFont.variable} bg-white`}>
        <NavbarComponent />
        <main className="xl:pt-[116px] md:pt-[96px] pt-[95px]">
          {children}
        </main>
        <FooterComponent />
      </body>
    </html>
  );
}
