import type { Metadata } from "next";
import "./globals.css";
import MyCustomFont from "../../public/assets/fonts/fonts";
import NavbarComponent from "@/app/components/Navbar/Navbar";
import FooterComponent from "@/app/components/Footer/Footer";

export const metadata: Metadata = {
  title: "Techtimize",
  description: "Generated by create next app",
  openGraph: {
    title: "Techtimize",
    description: "Visit the official site of Techtimize",
    url: "https://www.techtimize.org/",
    siteName: "techtimize.org",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${MyCustomFont.variable} bg-white`}>
        <NavbarComponent />
        <main className="pt-[120px]">{children}</main>
        <FooterComponent />
      </body>
    </html>
  );
}
